/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Session;


import Session.Session;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ViewSession extends javax.swing.JFrame {

    /**
     * Creates new form ViewSession
     */
    public ViewSession() {
        initComponents();
     
    }
    
    
//     public void showData(){
//        
//        try{
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/spm","root","");
//            Statement st=conn.createStatement();
//            String selectQuery="select * from session";
//            ResultSet rs=st.executeQuery(selectQuery);
//             while(rs.next())
//             {
//             String lecturer1=rs.getString(2);
//             String lecturer2=rs.getString(3);
//             
//             
//             
//             info.setText(lecturer1+","+lecturer2);
//             }
//
//             }catch(Exception e ){
//            JOptionPane.showMessageDialog(null,e);
//        }
//    }
    
      public ArrayList<Session>userList(){
        ArrayList<Session>sessionList=new ArrayList<>();
        
         try{
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/spm","root","");
    
            String query="select * from session";
            Statement st=conn.createStatement();
            
            ResultSet rs=st.executeQuery(query);
            
            Session session;
            
            while(rs.next()){
                session=new Session
               (
                  rs.getString("lecturer1"),
                  rs.getString("lecturer2"),
                  rs.getString("lecturer3"),
                  rs.getString("lecturer4"),
                  rs.getString("tag"),
                  rs.getString("studentGroup"),
                  rs.getString("subject"),
                  rs.getString("no_of_students"),
                  rs.getString("subgroup"),
                  rs.getString("sessionDuration")
         
               );
                
                sessionList.add(session);
                
            }
            
        }catch(Exception e ){
            JOptionPane.showMessageDialog(null,e);
        }
         return sessionList;
         
    }
      
          public void show_user(){
        ArrayList<Session> list=sessionList();
        
        
     DefaultTableModel  model = (DefaultTableModel)jTable_display.getModel();
    Object[] row =new Object[9];
    for(int i =0;i<list.size();i++){
        row[0]=list.get(i).getfirstname();
        row[1]=list.get(i).getlastname();
         row[2]=list.get(i).getempid();
         row[3]=list.get(i).getfaculty();
         row[4]=list.get(i).getbuilding();
        row[5]=list.get(i).getcenter();
          row[6]=list.get(i).getdepartment();
         row[7]=list.get(i).getlevel();
        row[8]=list.get(i).getrank();
       
         
        model.addRow(row);

                
    }
      
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSession().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
