/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workingdays;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author asvin
 */
public class UpdateWorkingDays extends javax.swing.JFrame {

    /**
     * Creates new form UpdateWorkingDays
     */
    public UpdateWorkingDays() {
        initComponents();
        show_user();
    }

     public ArrayList<User> userList(){
        ArrayList<User> usersList = new ArrayList<>();
        try{
           Class.forName("com.mysql.jdbc.Driver");
           
           Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/tms","root","");
           String query = "SELECT* FROM workingdays";
           Statement st = conn.createStatement();
           ResultSet rs = st.executeQuery(query);
           User user;
           while(rs.next()){
               user = new User(rs.getString("empID"), rs.getString("empName"),rs.getInt("dayNo"),rs.getString("wDays"),rs.getString("wTimePerDay"),rs.getString("timeSlot") );
               usersList.add(user);
           }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null,e);
        }
        return usersList;
    }
    public void show_user(){
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = new Object[6];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getempID();
            row[1]=list.get(i).getempName();
            row[2]=list.get(i).getdayNo();
            row[3]=list.get(i).getwDays();
            row[4]=list.get(i).getwTimePerDay();
            row[5]=list.get(i).gettimeSlot();
            model.addRow(row);
            
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        empName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        wdays = new javax.swing.JLabel();
        Monday = new javax.swing.JCheckBox();
        Tuesday = new javax.swing.JCheckBox();
        Wednesday = new javax.swing.JCheckBox();
        Thursday = new javax.swing.JCheckBox();
        Friday = new javax.swing.JCheckBox();
        Saturday = new javax.swing.JCheckBox();
        Sunday = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        wTimePerDay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dayNo = new javax.swing.JComboBox<>();
        timeSlot = new javax.swing.JComboBox<>();
        Update = new javax.swing.JButton();
        empID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        delete_empID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(210, 160, 138));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText(" Working Days & Hours");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmployeeID", "Employee Name", "NoOfWorkingDay/Week", "Working Days", "Working Time/Day", "Time Slot"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Employee Name :");

        empName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("No of Working Days per Week:");

        wdays.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wdays.setText("Working Days:");

        Monday.setText("Monday");
        Monday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MondayActionPerformed(evt);
            }
        });

        Tuesday.setText("Tuesday");
        Tuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuesdayActionPerformed(evt);
            }
        });

        Wednesday.setText("Wednesday");
        Wednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WednesdayActionPerformed(evt);
            }
        });

        Thursday.setText("Thursday");
        Thursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThursdayActionPerformed(evt);
            }
        });

        Friday.setText("Friday");
        Friday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FridayActionPerformed(evt);
            }
        });

        Saturday.setText("Saturday");

        Sunday.setText("Sunday");
        Sunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SundayActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Working Time per Day:");

        wTimePerDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wTimePerDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wTimePerDayActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Time Slot:");

        dayNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dayNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        timeSlot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timeSlot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Hour", "30 Min" }));
        timeSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotActionPerformed(evt);
            }
        });

        Update.setBackground(new java.awt.Color(210, 160, 138));
        Update.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        empID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Employee ID : ");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        delete.setBackground(new java.awt.Color(210, 160, 138));
        delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        delete_empID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Employee ID :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(delete_empID, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_empID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(wdays)
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Thursday)
                                            .addComponent(Monday)
                                            .addComponent(Sunday)))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Update)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayNo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tuesday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Wednesday))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Friday)
                                .addGap(18, 18, 18)
                                .addComponent(Saturday))
                            .addComponent(wTimePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(empName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dayNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wdays)
                            .addComponent(Monday)
                            .addComponent(Tuesday)
                            .addComponent(Wednesday))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Thursday)
                            .addComponent(Friday)
                            .addComponent(Saturday))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sunday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(wTimePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(26, 26, 26)
                                .addComponent(timeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(58, 58, 58)
                        .addComponent(Update)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(367, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FridayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FridayActionPerformed

    private void SundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SundayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SundayActionPerformed

    private void WednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WednesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WednesdayActionPerformed

    private void ThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThursdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThursdayActionPerformed
    String general_code;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        String something = empID.getText();
        general_code = something;
        
        TableModel model = jTable1.getModel();
        empID.setText(model.getValueAt(i,0).toString());
        empName.setText(model.getValueAt(i,1).toString());
       String dayNo1 = model.getValueAt(i,2).toString();
       switch(dayNo1){
        case "1":
           dayNo.setSelectedIndex(0);
           break;
        case "2":
           dayNo.setSelectedIndex(1);
           break;
        case "3":
           dayNo.setSelectedIndex(2);
           break;
        case "4":
           dayNo.setSelectedIndex(3);
           break;
        case "5":
           dayNo.setSelectedIndex(4);
           break;
        case "6":
           dayNo.setSelectedIndex(5);
           break;
        case "7":
           dayNo.setSelectedIndex(6);
           break;
       }
        String wdays = model.getValueAt(i,3).toString();
        switch(wdays){
            case "Monday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Wednesday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Thursday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Tuesday ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
                 case "TuesDay Wednesday ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "TuesDay ThursDay ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "TuesDay Friday ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "TuesDay SaturDay ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "TuesDay Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
             case "Wednesday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Wednesday Thursday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Wednesday Friday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break; 
            case "Wednesday Saturday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;  
            case "Wednesday Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;  
            case "Thursday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;   
            case "Thursday Friday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;   
            case "Thursday Saturday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;  
            case "Thursday Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;  
            case "Friday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;   
            case "Friday Saturday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;   
            case "Friday Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;   
            case "Saturday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;  
            case "Saturday Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;  
            case "Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;  
            case "Monday Tuesday Wednesday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Monday Tuesday Thursday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break; 
            case "Monday Tuesday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Monday Tuesday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break; 
            case "Monday Tuesday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;  
            case "Monday Wednesday Thursday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Monday Wednesday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Monday Wednesday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break; 
            case "Monday Wednesday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;  
            case "Monday Thursday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;  
            case "Monday Thursday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
             case "Monday Thursday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
             case "Monday Friday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;
             case "Monday Friday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Saturday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday Thursday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday Thursday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Thursday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Thursday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday Thursday Friday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Thursday Friday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday Thursday Friday Saturday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;   
            default:
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break; 
                
                
        }
        wTimePerDay.setText(model.getValueAt(i,4).toString()); 
        String timeSlot1 = model.getValueAt(i,5).toString();
        switch(timeSlot1){
            case "1 Hour":
                timeSlot.setSelectedIndex(0);
                break;
            case "30 Min":
                timeSlot.setSelectedIndex(1);
                break;
        }
        
    }//GEN-LAST:event_jTable1MouseClicked
   
    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        try{
           Class.forName("com.mysql.jdbc.Driver");
           
           Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/tms","root","");
           int row = jTable1.getSelectedRow();
           String value = (jTable1.getModel().getValueAt(row, 0).toString());
           String empId = empID.getText();
           
           
           String emp_Name = empName.getText();
           String day_No;
           day_No=dayNo.getSelectedItem().toString();
           //String w_days = wdays.getText();
           String w_days="";
          if(Monday.isSelected()){
              w_days+=Monday.getText()+" ";
          }
          if(Tuesday.isSelected()){
              w_days+=Tuesday.getText()+" ";
          }
          if(Wednesday.isSelected()){
              w_days+=Wednesday.getText()+" ";
          }
          if(Thursday.isSelected()){
              w_days+=Thursday.getText()+" ";
          }
          if(Friday.isSelected()){
              w_days+=Friday.getText()+" ";
          }
          if(Saturday.isSelected()){
              w_days+=Saturday.getText()+" ";
          }
          if(Sunday.isSelected()){
              w_days+=Sunday.getText()+" ";
          }
           String w_TimePerDay = wTimePerDay.getText();
           String time_Slot;
           time_Slot=timeSlot.getSelectedItem().toString();
           
           
          String query = "UPDATE workingdays SET empName='"+emp_Name+"', dayNo='"+day_No+"', wDays='"+w_days+"', wTimePerDay='"+w_TimePerDay+"', timeSlot='"+time_Slot+"' where empID='"+empId+"'";
          
          PreparedStatement pst = conn.prepareStatement(query);

          pst.executeUpdate();
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         model.setRowCount(0);
         show_user();
         JOptionPane.showMessageDialog(null,"Updated Sucessfully!");
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
        
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/tms","root","");
        String query="DELETE FROM workingdays WHERE empID ="+delete_empID.getText();
        Statement st=conn.createStatement();
       
        
        st.executeUpdate(query);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         model.setRowCount(0);
       show_user();
         JOptionPane.showMessageDialog(null,"Deleted Sucessfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }  
        
    }//GEN-LAST:event_deleteActionPerformed

    private void MondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MondayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MondayActionPerformed

    private void TuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuesdayActionPerformed

    private void wTimePerDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wTimePerDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wTimePerDayActionPerformed

    private void timeSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSlotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeSlotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateWorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateWorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateWorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateWorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateWorkingDays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Friday;
    private javax.swing.JCheckBox Monday;
    private javax.swing.JCheckBox Saturday;
    private javax.swing.JCheckBox Sunday;
    private javax.swing.JCheckBox Thursday;
    private javax.swing.JCheckBox Tuesday;
    private javax.swing.JButton Update;
    private javax.swing.JCheckBox Wednesday;
    private javax.swing.JComboBox<String> dayNo;
    private javax.swing.JButton delete;
    private javax.swing.JTextField delete_empID;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField empName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> timeSlot;
    private javax.swing.JTextField wTimePerDay;
    private javax.swing.JLabel wdays;
    // End of variables declaration//GEN-END:variables
}
